# Automatically generated by generate.jl from edm4hep.yaml (schema version 1)
schema_version = v"1"

"""
edm4hep!Vector2f
# Fields
- `a::Float32`: 
- `b::Float32`: 
"""
struct edm4hep!Vector2f <: POD
    a::Float32                       
    b::Float32                       
    edm4hep!Vector2f(a=0, b=0) = new(a, b)
end

Base.convert(::Type{edm4hep!Vector2f}, t::Tuple) = edm4hep!Vector2f(t...)
Base.convert(::Type{edm4hep!Vector2f}, v::@NamedTuple{a::Float32, b::Float32}) = edm4hep!Vector2f(v.a, v.b)

"""
Generic vector for storing classical 4D coordinates in memory. Four momentum helper functions are in edm4hep::utils
# Fields
- `x::Float32`: 
- `y::Float32`: 
- `z::Float32`: 
- `t::Float32`: 
"""
struct edm4hep!Vector4f <: POD
    x::Float32                       
    y::Float32                       
    z::Float32                       
    t::Float32                       
    edm4hep!Vector4f(x=0, y=0, z=0, t=0) = new(x, y, z, t)
end

Base.convert(::Type{edm4hep!Vector4f}, t::Tuple) = edm4hep!Vector4f(t...)
Base.convert(::Type{edm4hep!Vector4f}, v::@NamedTuple{x::Float32, y::Float32, z::Float32, t::Float32}) = edm4hep!Vector4f(v.x, v.y, v.z, v.t)

"""
edm4hep!Vector2i
# Fields
- `a::Int32`: 
- `b::Int32`: 
"""
struct edm4hep!Vector2i <: POD
    a::Int32                         
    b::Int32                         
    edm4hep!Vector2i(a=0, b=0) = new(a, b)
end

Base.convert(::Type{edm4hep!Vector2i}, t::Tuple) = edm4hep!Vector2i(t...)
Base.convert(::Type{edm4hep!Vector2i}, v::@NamedTuple{a::Int32, b::Int32}) = edm4hep!Vector2i(v.a, v.b)

"""
edm4hep!Hypothesis
# Fields
- `chi2::Float32`: chi2
- `expected::Float32`: expected value
- `sigma::Float32`: sigma value
"""
struct edm4hep!Hypothesis <: POD
    chi2::Float32                    # chi2
    expected::Float32                # expected value
    sigma::Float32                   # sigma value
    edm4hep!Hypothesis(chi2=0, expected=0, sigma=0) = new(chi2, expected, sigma)
end

Base.convert(::Type{edm4hep!Hypothesis}, t::Tuple) = edm4hep!Hypothesis(t...)
Base.convert(::Type{edm4hep!Hypothesis}, v::@NamedTuple{chi2::Float32, expected::Float32, sigma::Float32}) = edm4hep!Hypothesis(v.chi2, v.expected, v.sigma)

"""
edm4hep!Vector3f
# Fields
- `x::Float32`: 
- `y::Float32`: 
- `z::Float32`: 
"""
struct edm4hep!Vector3f <: POD
    x::Float32                       
    y::Float32                       
    z::Float32                       
    edm4hep!Vector3f(x=0, y=0, z=0) = new(x, y, z)
end

Base.convert(::Type{edm4hep!Vector3f}, t::Tuple) = edm4hep!Vector3f(t...)
Base.convert(::Type{edm4hep!Vector3f}, v::@NamedTuple{x::Float32, y::Float32, z::Float32}) = edm4hep!Vector3f(v.x, v.y, v.z)

"""
edm4hep!TrackState
# Fields
- `location::Int32`: for use with At{Other|IP|FirstHit|LastHit|Calorimeter|Vertex}|LastLocation
- `D0::Float32`: transverse impact parameter
- `phi::Float32`: azimuthal angle
- `omega::Float32`: is the signed curvature of the track in [1/mm].
- `Z0::Float32`: longitudinal impact parameter
- `tanLambda::Float32`: lambda is the dip angle of the track in r-z
- `time::Float32`: time of the track at this trackstate
- `referencePoint::edm4hep!Vector3f`: Reference point of the track parameters, e.g. the origin at the IP, or the position  of the first/last hits or the entry point into the calorimeter. [mm]
- `covMatrix::SVector{21,Float32}`: lower triangular covariance matrix of the track parameters.  the order of parameters is  d0, phi, omega, z0, tan(lambda), time. the array is a row-major flattening of the matrix.
"""
struct edm4hep!TrackState <: POD
    location::Int32                  # for use with At{Other|IP|FirstHit|LastHit|Calorimeter|Vertex}|LastLocation
    D0::Float32                      # transverse impact parameter
    phi::Float32                     # azimuthal angle
    omega::Float32                   # is the signed curvature of the track in [1/mm].
    Z0::Float32                      # longitudinal impact parameter
    tanLambda::Float32               # lambda is the dip angle of the track in r-z
    time::Float32                    # time of the track at this trackstate
    referencePoint::edm4hep!Vector3f # Reference point of the track parameters, e.g. the origin at the IP, or the position  of the first/last hits or the entry point into the calorimeter. [mm]
    covMatrix::SVector{21,Float32}   # lower triangular covariance matrix of the track parameters.  the order of parameters is  d0, phi, omega, z0, tan(lambda), time. the array is a row-major flattening of the matrix.
    edm4hep!TrackState(location=0, D0=0, phi=0, omega=0, Z0=0, tanLambda=0, time=0, referencePoint=0, covMatrix=0) = new(location, D0, phi, omega, Z0, tanLambda, time, referencePoint, covMatrix)
end

Base.convert(::Type{edm4hep!TrackState}, t::Tuple) = edm4hep!TrackState(t...)
Base.convert(::Type{edm4hep!TrackState}, v::@NamedTuple{location::Int32, D0::Float32, phi::Float32, omega::Float32, Z0::Float32, tanLambda::Float32, time::Float32, referencePoint::edm4hep!Vector3f, covMatrix::SVector{21,Float32}}) = edm4hep!TrackState(v.location, v.D0, v.phi, v.omega, v.Z0, v.tanLambda, v.time, v.referencePoint, v.covMatrix)

"""
edm4hep!Quantity
# Fields
- `type::Int16`: flag identifying how to interpret the quantity
- `value::Float32`: value of the quantity
- `error::Float32`: error on the value of the quantity
"""
struct edm4hep!Quantity <: POD
    type::Int16                      # flag identifying how to interpret the quantity
    value::Float32                   # value of the quantity
    error::Float32                   # error on the value of the quantity
    edm4hep!Quantity(type=0, value=0, error=0) = new(type, value, error)
end

Base.convert(::Type{edm4hep!Quantity}, t::Tuple) = edm4hep!Quantity(t...)
Base.convert(::Type{edm4hep!Quantity}, v::@NamedTuple{type::Int16, value::Float32, error::Float32}) = edm4hep!Quantity(v.type, v.value, v.error)

"""
edm4hep!Vector3d
# Fields
- `x::Float64`: 
- `y::Float64`: 
- `z::Float64`: 
"""
struct edm4hep!Vector3d <: POD
    x::Float64                       
    y::Float64                       
    z::Float64                       
    edm4hep!Vector3d(x=0, y=0, z=0) = new(x, y, z)
end

Base.convert(::Type{edm4hep!Vector3d}, t::Tuple) = edm4hep!Vector3d(t...)
Base.convert(::Type{edm4hep!Vector3d}, v::@NamedTuple{x::Float64, y::Float64, z::Float64}) = edm4hep!Vector3d(v.x, v.y, v.z)

"""
edm4hep!HitLevelData
# Fields
- `cellID::UInt64`: cell id
- `N::UInt32`: number of reconstructed ionization cluster.
- `eDep::Float32`: reconstructed energy deposit [GeV].
- `pathLength::Float32`: track path length [mm].
"""
struct edm4hep!HitLevelData <: POD
    cellID::UInt64                   # cell id
    N::UInt32                        # number of reconstructed ionization cluster.
    eDep::Float32                    # reconstructed energy deposit [GeV].
    pathLength::Float32              # track path length [mm].
    edm4hep!HitLevelData(cellID=0, N=0, eDep=0, pathLength=0) = new(cellID, N, eDep, pathLength)
end

Base.convert(::Type{edm4hep!HitLevelData}, t::Tuple) = edm4hep!HitLevelData(t...)
Base.convert(::Type{edm4hep!HitLevelData}, v::@NamedTuple{cellID::UInt64, N::UInt32, eDep::Float32, pathLength::Float32}) = edm4hep!HitLevelData(v.cellID, v.N, v.eDep, v.pathLength)

const HitLevelData = edm4hep!HitLevelData
const Vector3d = edm4hep!Vector3d
const Quantity = edm4hep!Quantity
const Vector3f = edm4hep!Vector3f
const TrackState = edm4hep!TrackState
const Hypothesis = edm4hep!Hypothesis
const Vector2i = edm4hep!Vector2i
const Vector4f = edm4hep!Vector4f
const Vector2f = edm4hep!Vector2f
export HitLevelData, Vector3d, Quantity, Vector3f, TrackState, Hypothesis, Vector2i, Vector4f, Vector2f
