# Automatically generated by generate.jl from edm4hep.yaml (schema version 6)

const edm4hep!CaloHitSimCaloHitLink = Link{edm4hep!CalorimeterHit,edm4hep!SimCalorimeterHit}
const edm4hep!CaloHitMCParticleLink = Link{edm4hep!CalorimeterHit,edm4hep!MCParticle}
const edm4hep!VertexRecoParticleLink = Link{edm4hep!Vertex,edm4hep!ReconstructedParticle}
const edm4hep!ClusterMCParticleLink = Link{edm4hep!Cluster,edm4hep!MCParticle}
const edm4hep!RecoMCParticleLink = Link{edm4hep!ReconstructedParticle,edm4hep!MCParticle}
const edm4hep!TrackMCParticleLink = Link{edm4hep!Track,edm4hep!MCParticle}
const edm4hep!TrackerHitSimTrackerHitLink = Link{edm4hep!TrackerHit,edm4hep!SimTrackerHit}

#---Aliases for easier access
const CaloHitSimCaloHitLink = edm4hep!CaloHitSimCaloHitLink
const CaloHitMCParticleLink = edm4hep!CaloHitMCParticleLink
const VertexRecoParticleLink = edm4hep!VertexRecoParticleLink
const ClusterMCParticleLink = edm4hep!ClusterMCParticleLink
const RecoMCParticleLink = edm4hep!RecoMCParticleLink
const TrackMCParticleLink = edm4hep!TrackMCParticleLink
const TrackerHitSimTrackerHitLink = edm4hep!TrackerHitSimTrackerHitLink


#---Exports
export CaloHitSimCaloHitLink, CaloHitMCParticleLink, VertexRecoParticleLink, ClusterMCParticleLink, RecoMCParticleLink, TrackMCParticleLink, TrackerHitSimTrackerHitLink
